// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Transaction pooler URL for serverless (Vercel)
    url: process.env["DATABASE_URL"],
    // Direct URL for migrations
    directUrl: process.env["DIRECT_URL"],
  },
});
